# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets: # Contient la liste des filtres
    mini: # Nom du filtre
      quality: 75 # Qualité de l'image
      filters: # Liste des filtres à appliquer
        thumbnail: { size: [ 52, 52 ], mode: outbound }


    max: # Nom du filtre
      quality: 75 # Qualité de l'image
      filters: # Liste des filtres à appliquer
        thumbnail: { size: [ 500, 500 ], mode: outbound }